### ISSUE TITLE
No device

### ISSUE THREAD

**Issue by dartymath** [MTrab/landroid_cloud#397]
### Describe the issue

After update of HA and supervisor to :
Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.3
Integration stop to work with an error on configuration and show no device and entities

### What version of Home Assistant Core has the issue?

2023.6.2

### What version of the Landroid Cloud integration do you have installed

Last

### What type of installation are you running?

Home Assistant OS

### Which make and model is the mower used for this integration?

Landroid M500

### Diagnostics information (NOT log entries!)

Not possible with the new version

### Relevant log entries

```txt
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant.config_entries
Source: custom_components/landroid_cloud/__init__.py:206 
Integration: Landroid Cloud (documentation, issues) 
First occurred: 20:34:21 (6 occurrences) 
Last logged: 23:16:38

Error setting up entry Worx - mathias.ibert@free.fr for landroid_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 63, in async_setup_entry
    result = await _async_setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/landroid_cloud/__init__.py", line 206, in _async_setup
    await hass.async_add_executor_job(cloud.connect)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 259, in connect
    self._fetch()
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 607, in _fetch
    self._decode_data(device)
  File "/usr/local/lib/python3.11/site-packages/pyworxcloud/__init__.py", line 450, in _decode_data
    device.updated = data["cfg"]["dt"] + " " + data["cfg"]["tm"]
                     ~~~~~~~~~~~^^^^^^
KeyError: 'dt'
```

**Comment by MTrab** [comment]
Should be fixed in v3.0.5

**Comment by dartymath** [comment]
Hello, after update, the issue is still there ! No device show ! The vision and the previous Landroid did appear now in HA

**Comment by MTrab** [comment]
As mentioned in #366 the Vision line is not supported yet

**Comment by dartymath** [comment]
I know for the Landroid vision, my point is that my other Landroid M didn't show also
