### ISSUE TITLE
No Device & service

### ISSUE THREAD

**Issue by maury77** [MTrab/landroid_cloud#64]
I have the versione 2021.6.0 and not found device or service

[custom_components.landroid_cloud] Connecting to device ID 0 (xxx.xxx@gmail.com)

2021-06-03 20:03:47 ERROR (MainThread) [homeassistant.setup] Setup of landroid_cloud is taking longer than 300 seconds. Startup will proceed without waiting any longer

I try to unpair .. but none

**Comment by MrGravgaard** [comment]
I haven't got one either on version 2021.6.1. I get a missing version number in manifest - which is wrong because it is there. 

This might be your underlying error. 

Error from log: 
2021-06-04 10:02:18 ERROR (SyncWorker_4) [homeassistant.loader] The custom integration 'landroid_cloud' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

Manifest: 
{
  "domain": "landroid_cloud",
  "name": "Worx Landroid Cloud",
  "documentation": "https://github.com/MTrab/landroid_cloud/blob/master/README.md",
  "issue_tracker": "https://github.com/MTrab/landroid_cloud/issues",
  "requirements": ["pyworxcloud==1.2.22"],
  "version": "1.6.6",
  "codeowners": ["@MTrab"]
}

**Comment by maury77** [comment]
I try with 2021.6.2 and I Have also 

[custom_components.landroid_cloud] Connecting to device ID 0 (xxx.xxx@gmail.com)

2021-06-03 20:03:47 ERROR (MainThread) [homeassistant.setup] Setup of landroid_cloud is taking longer than 300 seconds. Startup will proceed without waiting any longer

**Comment by MTrab** [comment]
Strange - just updated both my dev and prod envs, and have no errors on this component.

**Comment by maury77** [comment]
I have no problem with manifest for all version 

It seems that the component cannot connect, do I have to do some manual tests? with debug mode no error

**Comment by maury77** [comment]
any idea?

**Comment by rosscullen** [comment]
Running 2021.6.2 and no issues. Assume the Landroid app is working OK?

**Comment by maury77** [comment]
my proble in present on 

2021.5.5
2021.6.0
2021.6.2

Android APP is OK

MQTT-landroid-bridge is ok
Manual call API with SOAP UI is OK
this addon for me  block on this row  **await hass.async_add_executor_job(client[dev].connect, device, False)**

**Comment by MTrab** [comment]
Did this component ever work for you?

**Comment by maury77** [comment]
unfortunately I have never been able to get it going

Will there be something in my libraries?

**Comment by MTrab** [comment]
Perhaps some obscoure combination in your password. Thought I fixed that, but it have been an issue before.

Could you try changing your password to something different?

**Comment by maury77** [comment]
I tried to change the password twice but unfortunately it didn't solve, do I have  try some particular combination?

**Comment by MTrab** [comment]
Unfortunately no idea, as I cannot recreate the issue.
To investigate further I need access to your account info, to see if that will show same error on my test environment.

**Comment by maury77** [comment]
> Unfortunately no idea, as I cannot recreate the issue.
> To investigate further I need access to your account info, to see if that will show same error on my test environment.

ok for me , if you want I send you my credential . for the test

**Comment by maury77** [comment]
> Unfortunately no idea, as I cannot recreate the issue.
> To investigate further I need access to your account info, to see if that will show same error on my test environment.

can I contact you in private?

**Comment by MTrab** [comment]
Yes, sorry - been a little occupied :) But yes, you can send it to morten (at) trab.dk

**Comment by MTrab** [comment]
I see no problems, using you account.
![image](https://user-images.githubusercontent.com/14296463/122678965-27306400-d1e9-11eb-926e-68019fa2b091.png)
![image](https://user-images.githubusercontent.com/14296463/122678969-31526280-d1e9-11eb-85f8-04f2afcd26d1.png)

Unfortunately I have no idea, what is intefering in your setup, but the integration works like it's supposed to.

**Comment by MrGravgaard** [comment]
I reinstalled the custom_component: 
- removed it
- rebooted
- added it again from GitHub
- rebooted

That made it work.

**Comment by maury77** [comment]
> Non vedo problemi, utilizzando il tuo account.
> ![Immagine](https://user-images.githubusercontent.com/14296463/122678965-27306400-d1e9-11eb-926e-68019fa2b091.png)
> ![Immagine](https://user-images.githubusercontent.com/14296463/122678969-31526280-d1e9-11eb-85f8-04f2afcd26d1.png)
> 
> Sfortunatamente non ho idea di cosa stia interferendo nella tua configurazione, ma l'integrazione funziona come dovrebbe.


Unbelievable, too strange

What libraries does your component use? I try to look .. these..

**Comment by MTrab** [comment]
requirements = ['paho-mqtt==1.5.0',
                'pyOpenSSL==17.5.0']

**Comment by MTrab** [comment]
Those should be pretty standard for Home Assistant

**Comment by MichaIng** [comment]
Chiming in here to avoid [doubled conversations](https://github.com/MichaIng/DietPi/issues/4500). The Python environment should match, as it's installed via `pip3 install -r `[requirements.txt](https://github.com/home-assistant/core/blob/dev/requirements.txt) for the initial install and everything else is installed by HA itself on demand, as long as this plugin is installed via HA web UI and not manually.

It's a [pyenv](https://github.com/pyenv/pyenv) instead of a `venv` or `virtualenv`, which should however not effect the result. To check the environment
```
sudo -u homeassistant bash
. /home/homeassistant/pyenv-activate.sh
pip3 freeze
```

And just to rule it out, to upgrade the Python version from Python 3.8.5 to 3.8.10: `dietpi-software reintsall 157`
As HA stores the installed dependencies in a separate file in the data directory, it's recreated automatically.

**Comment by maury77** [comment]
aiohttp==3.7.4.post0
astral==2.2
async-timeout==3.0.1
attrs==21.2.0
awesomeversion==21.4.0
backports.zoneinfo==0.2.1
bcrypt==3.1.7
certifi==2020.12.5
cffi==1.14.3
chardet==3.0.4
ciso8601==2.1.3
cryptography==3.3.2
greenlet==1.1.0
h11==0.11.0
homeassistant==2021.6.5
httpcore==0.13.3
httpx==0.18.0
huawei-solar==0.0.11
idna==2.10
ifaddr==0.1.7
Jinja2==3.0.1
MarkupSafe==2.0.1
multidict==4.7.6
netifaces==0.10.9
numpy==1.19.2
paho-mqtt==1.5.1
protobuf==3.13.0
pyatv==0.7.2
pycparser==2.20
PyJWT==1.7.1
pymodbus==2.3.0
pyserial==3.4
python-slugify==4.0.1
PyTurboJPEG==1.4.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
rfc3986==1.4.0
ruamel.yaml==0.15.100
six==1.15.0
sniffio==1.2.0
SQLAlchemy==1.4.17
srptools==1.0.1
text-unidecode==1.3
typing-extensions==3.7.4.3
urllib3==1.25.10
voluptuous==0.12.1
voluptuous-serialize==2.4.0
yarl==1.6.3
zeroconf==0.28.5

**Comment by MichaIng** [comment]
Is `pyOpenSSL` a dependency? Also the `paho-mqtt` version does not match 100%. Just to rule it out:
```sh
sudo -u homeassistant bash
. /home/homeassistant/pyenv-activate.sh
pip3 install paho-mqtt==1.5.0 pyOpenSSL==17.5.0
exit
systemctl restart home-assistant
```

**Comment by maury77** [comment]
I try install the libraries but problem persist

2021-07-06 23:34:38 ERROR (MainThread) [homeassistant.setup] Setup of landroid_cloud is taking longer than 300 seconds. Startup will proceed without waiting any longer


homeassistant@sdomotica:~$ pip3 freeze
aiohttp==3.7.4.post0
astral==2.2
async-timeout==3.0.1
attrs==21.2.0
awesomeversion==21.4.0
backports.zoneinfo==0.2.1
bcrypt==3.1.7
certifi==2020.12.5
cffi==1.14.3
chardet==3.0.4
ciso8601==2.1.3
cryptography==3.3.2
greenlet==1.1.0
h11==0.11.0
homeassistant==2021.6.5
httpcore==0.13.3
httpx==0.18.0
huawei-solar==0.0.11
idna==2.10
ifaddr==0.1.7
Jinja2==3.0.1
MarkupSafe==2.0.1
multidict==4.7.6
netifaces==0.10.9
numpy==1.19.2
paho-mqtt==1.5.0
protobuf==3.13.0
pyatv==0.7.2
pycparser==2.20
PyJWT==1.7.1
pymodbus==2.3.0
pyOpenSSL==17.5.0
pyserial==3.4
python-slugify==4.0.1
PyTurboJPEG==1.4.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
rfc3986==1.4.0
ruamel.yaml==0.15.100
six==1.15.0
sniffio==1.2.0
SQLAlchemy==1.4.17
srptools==1.0.1
text-unidecode==1.3
typing-extensions==3.7.4.3
urllib3==1.25.10
voluptuous==0.12.1
voluptuous-serialize==2.4.0
yarl==1.6.3
zeroconf==0.28.5

**Comment by maury77** [comment]
There is a problem installing OpenSSL
The homekit integration no longer works correctly, the switches read correctly but do not modify
Removing pyOpenSSL everything works again

**Comment by maury77** [comment]
I have try to insert some row of log the problem is on istruction

        _LOGGER.info("MQTT connect url %s",self._worx_mqtt_client_id)    
        **conn_res = self._mqtt.connect(self._worx_mqtt_endpoint, port=8883, keepalive=600)**
        _LOGGER.info("MQTT after connect workx")      

the time of wait of connect is upper thand timeout of plugin 

![image](https://user-images.githubusercontent.com/35746732/125190483-aa1f6a00-e23d-11eb-8636-04b63d9ddc60.png)

**Comment by MTrab** [comment]
Do you have a firewall somewhere, blocking for outgoing connection on port 8883?
Or perhaps your ISP have?

**Comment by maury77** [comment]
> Hai un firewall da qualche parte, che blocca la connessione in uscita sulla porta 8883?
> O forse il tuo ISP ha?

No block By isp and virtualzone landroid bridge work correctly

**Comment by maury77** [comment]
Could it conflict with my local broker?

**Comment by MTrab** [comment]
Could be a conflict.

**Comment by maury77** [comment]
what do you recommend to solve?
thanks

**Comment by MTrab** [comment]
Sorry, but I have absolutely no idea, as I cannot reproduce this

**Comment by maury77** [comment]
I solved the problem with disable IPV6 option of dietpi

**Comment by MichaIng** [comment]
Interesting. I the MQTT server actually listening on IPv6?
```sh
ss -tulpn
```

**Comment by maury77** [comment]
ss -tulpn
Netid                  State                   Recv-Q                  Send-Q                                     Local Address:Port                                     Peer Address:Port                                                                                             
udp                    UNCONN                  0                       0                                                0.0.0.0:52194                                         0.0.0.0:*                      users:(("hass",pid=823,fd=24))                                            
udp                    UNCONN                  0                       0                                                0.0.0.0:34320                                         0.0.0.0:*                      users:(("node-red",pid=712,fd=18))                                        
udp                    UNCONN                  0                       0                                                0.0.0.0:54317                                         0.0.0.0:*                      users:(("hass",pid=823,fd=34))                                            
udp                    UNCONN                  0                       0                                                0.0.0.0:5683                                          0.0.0.0:*                      users:(("hass",pid=823,fd=37))                                            
udp                    UNCONN                  0                       0                                                0.0.0.0:111                                           0.0.0.0:*                      users:(("rpcbind",pid=272,fd=5),("systemd",pid=1,fd=55))                  
udp                    UNCONN                  0                       0                                          192.168.0.255:137                                           0.0.0.0:*                      users:(("nmbd",pid=640,fd=17))                                            
udp                    UNCONN                  0                       0                                           192.168.0.93:137                                           0.0.0.0:*                      users:(("nmbd",pid=640,fd=16))                                            
udp                    UNCONN                  0                       0                                                0.0.0.0:137                                           0.0.0.0:*                      users:(("nmbd",pid=640,fd=14))                                            
udp                    UNCONN                  0                       0                                          192.168.0.255:138                                           0.0.0.0:*                      users:(("nmbd",pid=640,fd=19))                                            
udp                    UNCONN                  0                       0                                           192.168.0.93:138                                           0.0.0.0:*                      users:(("nmbd",pid=640,fd=18))                                            
udp                    UNCONN                  0                       0                                                0.0.0.0:138                                           0.0.0.0:*                      users:(("nmbd",pid=640,fd=15))                                            
udp                    UNCONN                  0                       0                                             224.0.0.50:9898                                          0.0.0.0:*                      users:(("hass",pid=823,fd=39))                                            
udp                    UNCONN                  0                       0                                                0.0.0.0:51413                                         0.0.0.0:*                      users:(("transmission-da",pid=681,fd=19))                                 
udp                    UNCONN                  0                       0                                                0.0.0.0:5353                                          0.0.0.0:*                      users:(("hass",pid=823,fd=41))                                            
udp                    UNCONN                  0                       0                                                0.0.0.0:5353                                          0.0.0.0:*                      users:(("node-red",pid=712,fd=19))                                        
udp                    UNCONN                  0                       0                                                0.0.0.0:5353                                          0.0.0.0:*                      users:(("librespot",pid=704,fd=19))                                       
udp                    UNCONN                  0                       0                                                0.0.0.0:5353                                          0.0.0.0:*                      users:(("homebridge",pid=1196,fd=20))                                     
udp                    UNCONN                  0                       0                                                0.0.0.0:5353                                          0.0.0.0:*                      users:(("hb-service",pid=1185,fd=20))                                     
udp                    UNCONN                  0                       0                                        239.255.255.250:1900                                          0.0.0.0:*                      users:(("hass",pid=823,fd=57))                                            
udp                    UNCONN                  0                       0                                                      *:111                                                 *:*                      users:(("rpcbind",pid=272,fd=7),("systemd",pid=1,fd=58))                  
tcp                    LISTEN                  0                       100                                         192.168.0.93:51828                                         0.0.0.0:*                      users:(("hass",pid=823,fd=43))                                            
tcp                    LISTEN                  0                       100                                         192.168.0.93:51829                                         0.0.0.0:*                      users:(("hass",pid=823,fd=35))                                            
tcp                    LISTEN                  0                       128                                              0.0.0.0:51413                                         0.0.0.0:*                      users:(("transmission-da",pid=681,fd=17))                                 
tcp                    LISTEN                  0                       128                                              0.0.0.0:22                                            0.0.0.0:*                      users:(("sshd",pid=575,fd=3))                                             
tcp                    LISTEN                  0                       511                                              0.0.0.0:1880                                          0.0.0.0:*                      users:(("node-red",pid=712,fd=21))                                        
tcp                    LISTEN                  0                       1024                                             0.0.0.0:36921                                         0.0.0.0:*                      users:(("librespot",pid=704,fd=18))                                       
tcp                    LISTEN                  0                       128                                              0.0.0.0:8123                                          0.0.0.0:*                      users:(("hass",pid=823,fd=29))                                            
tcp                    LISTEN                  0                       50                                               0.0.0.0:445                                           0.0.0.0:*                      users:(("smbd",pid=651,fd=31))                                            
tcp                    LISTEN                  0                       64                                               0.0.0.0:39103                                         0.0.0.0:*                                                                                                
tcp                    LISTEN                  0                       128                                              0.0.0.0:9091                                          0.0.0.0:*                      users:(("transmission-da",pid=681,fd=16))                                 
tcp                    LISTEN                  0                       5                                              127.0.0.1:6600                                          0.0.0.0:*                      users:(("mpd",pid=665,fd=12))                                             
tcp                    LISTEN                  0                       50                                               0.0.0.0:139                                           0.0.0.0:*                      users:(("smbd",pid=651,fd=32))                                            
tcp                    LISTEN                  0                       128                                              0.0.0.0:111                                           0.0.0.0:*                      users:(("rpcbind",pid=272,fd=4),("systemd",pid=1,fd=54))                  
tcp                    LISTEN                  0                       128                                                 [::]:51413                                            [::]:*                      users:(("transmission-da",pid=681,fd=18))                                 
tcp                    LISTEN                  0                       128                                                 [::]:22                                               [::]:*                      users:(("sshd",pid=575,fd=4))                                             
tcp                    LISTEN                  0                       511                                                    *:3000                                                *:*                      users:(("sdomotica",pid=508,fd=30))                                       
tcp                    LISTEN                  0                       64                                                  [::]:40793                                            [::]:*                                                                                                
tcp                    LISTEN                  0                       511                                                    *:3002                                                *:*                      users:(("sdomotica",pid=508,fd=20))                                       
tcp                    LISTEN                  0                       128                                                 [::]:8123                                             [::]:*                      users:(("hass",pid=823,fd=30))                                            
tcp                    LISTEN                  0                       511                                                    *:1883                                                *:*                      users:(("mqtt",pid=511,fd=19))                                            
tcp                    LISTEN                  0                       511                                                    *:3100                                                *:*                      users:(("sdomotica",pid=508,fd=27))                                       
tcp                    LISTEN                  0                       50                                                  [::]:445                                              [::]:*                      users:(("smbd",pid=651,fd=29))                                            
tcp                    LISTEN                  0                       511                                                    *:3200                                                *:*                      users:(("sdomotica",pid=508,fd=32))                                       
tcp                    LISTEN                  0                       511                                                    *:3201                                                *:*                      users:(("sdomoticawwl",pid=506,fd=20))                                    
tcp                    LISTEN                  0                       511                                                    *:3300                                                *:*                      users:(("sdomotica",pid=508,fd=19))                                       
tcp                    LISTEN                  0                       511                                                    *:8581                                                *:*                      users:(("hb-service",pid=1185,fd=22))                                     
tcp                    LISTEN                  0                       5                                                  [::1]:6600                                             [::]:*                      users:(("mpd",pid=665,fd=11))                                             
tcp                    LISTEN                  0                       50                                                  [::]:139                                              [::]:*                      users:(("smbd",pid=651,fd=30))                                            
tcp                    LISTEN                  0                       128                                                 [::]:111                                              [::]:*                      users:(("rpcbind",pid=272,fd=6),("systemd",pid=1,fd=57))                  
tcp                    LISTEN                  0                       511                                                    *:51827                                               *:*                      users:(("homebridge",pid=1196,fd=19))

**Comment by maury77** [comment]
I have a similar problem with new version of hacs 

https://github.com/hacs/integration/issues/2186#issuecomment-907689741

with disable option a solved both problem

**Comment by MichaIng** [comment]
```
tcp LISTEN 0 511 *:1883 : users:(("mqtt",pid=511,fd=19))
```
That notation indicates that it listens on both, IPv4 and IPv6. Compare to
```
tcp LISTEN 0 128 0.0.0.0:8123 0.0.0.0:* users:(("hass",pid=823,fd=29))
tcp LISTEN 0 128 [::]:8123 [::]: users:(("hass",pid=823,fd=30))
...
where the first is IPv4 only and the second IPv6 only.

Would be interesting to know why IPv6 is the issue here. I left the question at the HACS issue, as ludeeus was immediately able to know that IPv6 is the issue, and it would be quite interesting to understand why or in which circumstances, so we may be able to fix or work around it DietPi-wise, or at least add a hint to our docs.

**Comment by maury77** [comment]
The Connection of this plugin is versus iot aws Service of landroid cloud

**Comment by MichaIng** [comment]
So it seems to be a bug in HA core itself, trying to connect via IPv6 to hosts which do not even have an AAAA DNS record.
